spring.application.name=speed-violation-service

server.port=${SERVER_PORT:8080}

violation.tolerance.fixed-kmh=${TOLERANCE_FIXED_KMH:7}
violation.tolerance.percentage=${TOLERANCE_PERCENTAGE:7}
violation.tolerance.percentage-threshold=${TOLERANCE_PERCENTAGE_THRESHOLD:100}
